### ISSUE TITLE
Add Ethical Hacking Resources

### ISSUE THREAD

**Issue by yashovardhanagrawal** [Cybros/Ethical-Hacking#1]
Kindly add resources related to **Ethical Hacking**. These can be study materials, links, question papers, tools etc.
Please make sure you add everything in a **separate specified folder**.

**Comment by pr0me** [comment]
i would like to add a list of suggested books on the topic, is that fine?

**Comment by yashovardhanagrawal** [comment]
@pr0me 
For sure!
Add as many resources as you can! 
This repository has the aim to provide all possible resources to the people trying to explore Ethical Hacking as an area of interest.

**Comment by divyanshu-rawat** [comment]
@pr0me looking forward for your PR 👍
